server:
  port: 8001

spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/user_dev
    username: dev_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.user.entity

logging:
  level:
    com.example.user: DEBUG
