server:
  port: 8002

spring:
  application:
    name: order-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/order_dev
    username: dev_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver

feign:
  client:
    config:
      user-service:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    com.example.order: DEBUG
